#include "opcode.hpp"
#include "instruction_info.hpp"
#include <unordered_map>

// Registers info about each type of instruction
// NOTE: This should really be stored in a JSON file and read in
const std::unordered_map<Opcode, InstructionInfo> instructionRegistry = {
    {Opcode::INVALID, {"INVALID", "", ""}},

    {Opcode::LUI,     {"LUI", "RI", ""  }},
    {Opcode::LLI,     {"LLI", "RI", ""  }},
    {Opcode::LOAD8,   {"LOAD8", "RRI", "" }},
    {Opcode::LOADU8,  {"LOADU8", "RRI", "" }},
    {Opcode::LOAD16,  {"LOAD16", "RRI", "" }},
    {Opcode::LOADU16, {"LOADU16", "RRI", "" }},
    {Opcode::LOAD32,  {"LOAD32", "RRI", "" }},
    {Opcode::LOADU32, {"LOADU32", "RRI", "" }},
    {Opcode::LOAD64,  {"LOAD64", "RRI", "" }},
    {Opcode::STORE8,  {"STORE8", "RRI", "" }},
    {Opcode::STORE16, {"STORE16", "RRI", "" }},
    {Opcode::STORE32, {"STORE32", "RRI", "" }},
    {Opcode::STORE64, {"STORE64", "RRI", "" }},

    {Opcode::ADD32, {"ADD32", "RRR", "" }},
    {Opcode::ADD64, {"ADD64", "RRR", "" }},
    {Opcode::SUB32, {"SUB32", "RRR", "" }},
    {Opcode::SUB64, {"SUB64", "RRR", "" }},
    {Opcode::MUL32, {"MUL32", "RRR", "" }},
    {Opcode::MUL64, {"MUL64", "RRR", "" }},
    {Opcode::DIVI32, {"DIVI32", "RRR", "" }},
    {Opcode::DIVI64, {"DIVI64", "RRR", "" }},
    {Opcode::DIVU32, {"DIVU32", "RRR", "" }},
    {Opcode::DIVU64, {"DIVU64", "RRR", "" }},
    {Opcode::MODI32, {"MODI32", "RRR", "" }},
    {Opcode::MODI64, {"MODI64", "RRR", "" }},
    {Opcode::MODU32, {"MODU32", "RRR", "" }},
    {Opcode::MODU64, {"MODU64", "RRR", "" }},

    {Opcode::ADD32I, {"ADD32I", "RRI", "" }},
    {Opcode::ADD64I, {"ADD64I", "RRI", "" }},
    {Opcode::SUB32I, {"SUB32I", "RRI", "" }},
    {Opcode::SUB64I, {"SUB64I", "RRI", "" }},
    {Opcode::MUL32I, {"MUL32I", "RRI", "" }},
    {Opcode::MUL64I, {"MUL64I", "RRI", "" }},
    {Opcode::DIVI32I, {"DIVI32I", "RRI", "" }},
    {Opcode::DIVI64I, {"DIVI64I", "RRI", "" }},
    {Opcode::DIVU32I, {"DIVU32I", "RRI", "" }},
    {Opcode::DIVU64I, {"DIVU64I", "RRI", "" }},
    {Opcode::MODI32I, {"MODI32I", "RRI", "" }},
    {Opcode::MODI64I, {"MODI64I", "RRI", "" }},
    {Opcode::MODU32I, {"MODU32I", "RRI", "" }},
    {Opcode::MODU64I, {"MODU64I", "RRI", "" }},

    {Opcode::ADDF32, {"ADDF32", "RRR", "" }},
    {Opcode::ADDF64, {"ADDF64", "RRR", "" }},
    {Opcode::SUBF32, {"SUBF32", "RRR", "" }},
    {Opcode::SUBF64, {"SUBF64", "RRR", "" }},
    {Opcode::MULF32, {"MULF32", "RRR", "" }},
    {Opcode::MULF64, {"MULF64", "RRR", "" }},
    {Opcode::DIVF32, {"DIVF32", "RRR", "" }},
    {Opcode::DIVF64, {"DIVF64", "RRR", "" }},
    {Opcode::SQRTF32, {"SQRTF32", "RRR", "" }},
    {Opcode::SQRTF64, {"SQRTF64", "RRR", "" }},
    {Opcode::ABSF32, {"ABSF32", "RRR", "" }},
    {Opcode::ABSF64, {"ABSF64", "RRR", "" }},
    {Opcode::NEGF32, {"NEGF32", "RRR", "" }},
    {Opcode::NEGF64, {"NEGF64", "RRR", "" }},

    {Opcode::SEXT8,     {"SEXT8", "RR", ""  }},
    {Opcode::SEXT16,    {"SEXT16", "RR", ""  }},
    {Opcode::SEXT32,    {"SEXT32", "RR", ""  }},
    {Opcode::ZEXT8,     {"ZEXT8", "RR", ""  }},
    {Opcode::ZEXT16,    {"ZEXT16", "RR", ""  }},
    {Opcode::ZEXT32,    {"ZEXT32", "RR", ""  }},
    {Opcode::CVTI32F32, {"CVTI32F32", "RR", ""  }},
    {Opcode::CVTI64F64, {"CVTI64F64", "RR", ""  }},
    {Opcode::CVTF32I32, {"CVTF32I32", "RR", ""  }},
    {Opcode::CVTF64I64, {"CVTF64I64", "RR", ""  }},
    {Opcode::CVTF64F32, {"CVTF64F32", "RR", ""  }},
    {Opcode::CVTF32F64, {"CVTF32F64", "RR", ""  }},

    {Opcode::SLL32, {"SLL32", "RRR", "" }},
    {Opcode::SLL64, {"SLL64", "RRR", "" }},
    {Opcode::SRL32, {"SRL32", "RRR", "" }},
    {Opcode::SRL64, {"SRL64", "RRR", "" }},
    {Opcode::SRA32, {"SRA32", "RRR", "" }},
    {Opcode::SRA64, {"SRA64", "RRR", "" }},
    {Opcode::OR64, {"OR64", "RRR", "" }},
    {Opcode::AND64, {"AND64", "RRR", "" }},
    {Opcode::XOR64, {"XOR64", "RRR", "" }},
    {Opcode::NOT32, {"NOT32", "RR", "" }},
    {Opcode::NOT64, {"NOT64", "RR", "" }},

    {Opcode::SLL32I, {"SLL32I", "RRI", "" }},
    {Opcode::SLL64I, {"SLL64I", "RRI", "" }},
    {Opcode::SRL32I, {"SRL32I", "RRI", "" }},
    {Opcode::SRL64I, {"SRL64I", "RRI", "" }},
    {Opcode::SRA32I, {"SRA32I", "RRI", "" }},
    {Opcode::SRA64I, {"SRA64I", "RRI", "" }},
    {Opcode::OR64I, {"OR64I", "RRI", "" }},
    {Opcode::AND64I, {"AND64I", "RRI", "" }},
    {Opcode::XOR64I, {"XOR64I", "RRI", "" }},

    {Opcode::BEQ, {"BEQ", "RRR", "" }},
    {Opcode::BNE, {"BNE", "RRR", "" }},
    {Opcode::BLT, {"BLT", "RRR", "" }},
    {Opcode::BGE, {"BGE", "RRR", "" }},
    {Opcode::BLTU, {"BLTU", "RRR", "" }},
    {Opcode::BGEU, {"BGEU", "RRR", "" }},
    {Opcode::JMP, {"JMP", "R", "" }},

    {Opcode::EQ,     {"EQ", "RRR", "" }},
    {Opcode::LT,     {"LT", "RRR", "" }},
    {Opcode::LTU,    {"LTU", "RRR", "" }},
    {Opcode::EQF32,  {"EQF32", "RRR", "" }},
    {Opcode::EQF64,  {"EQF64", "RRR", "" }},
    {Opcode::LTF32,  {"LTF32", "RRR", "" }},
    {Opcode::LTF64,  {"LTF64", "RRR", "" }},
    {Opcode::LEF32,  {"LEF32", "RRR", "" }},
    {Opcode::LEF64,  {"LEF64", "RRR", "" }},

    {Opcode::CALL, {"CALL", "R", "" }},
    {Opcode::SYSCALL, {"SYSCALL", "I", ""   }},
    {Opcode::RET, {"RET", "", ""}},
    {Opcode::PUSH, {"PUSH", "R", ""   }},
    {Opcode::POP, {"POP", "R", ""   }},

    {Opcode::NOP, {"NOP", "", ""}},
    {Opcode::HALT, {"HALT", "", ""}},
    {Opcode::GETCHAR, {"GETCHAR", "R", ""   }},
    {Opcode::PUTCHAR, {"PUTCHAR", "R", ""   }},
};

const InstructionInfo* getInstructionInfo(Opcode opcode) {
    auto it = instructionRegistry.find(opcode);
    return (it != instructionRegistry.end()) ? &it->second : nullptr;
}
